services:
    mundophpbb.simpledown.listener:
        class: mundophpbb\simpledown\event\listener
        arguments:
            - '@template'
            - '@controller.helper'
            - '@language'
        tags:
            - { name: event.listener }

    # Controller do frontend (página /downloads, download, preview, details)
    mundophpbb.simpledown.controller:
        class: mundophpbb\simpledown\controller\main_controller
        arguments:
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@path_helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
        tags:
            - { name: controller.service_arguments }

    # ACP: Controller para Configurações
    mundophpbb.simpledown.acp_settings_controller:
        class: mundophpbb\simpledown\controller\acp_settings_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@path_helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'

    # ACP: Controller para Listagem e Gerenciamento de Arquivos
    mundophpbb.simpledown.acp_files_controller:
        class: mundophpbb\simpledown\controller\acp_files_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@path_helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'

    # ACP: Controller para a página Ferramentas (Tools)
    mundophpbb.simpledown.acp_tools_controller:
        class: mundophpbb\simpledown\controller\acp_tools_controller
        arguments:
            - '@config'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'

    # ACP: Controller para a página de Logs
    mundophpbb.simpledown.acp_logs_controller:
        class: mundophpbb\simpledown\controller\acp_logs_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '%core.table_prefix%'
            - '@pagination'   # ← ADICIONADO: necessário para generate_template_pagination()